### ISSUE TITLE
How to run setup.vbs?

### ISSUE THREAD

**Issue by BlackRose-XIII** [YoruAlptraum/no-splash-opera-gx#2]
Hi, sorry to submit such a stupid issue but I couldn't reach you on Reddit. I'm not sure how to run the setup.vbs file; the istructions just say to "run" it so I tried double-clicking like an .exe but nothing happened. Is there a separate program or something I need to make this work?

**Comment by YoruAlptraum** [comment]
To run the setup.vbs you just need to double clicking it like a .exe. The vbs currently runs without a message, you can confirm it has worked by right clicking opera on the windows start menu > open file location > right click the shortcut that appears and check if the Target in properties now is set to `run_no_splash.vbs`.

you can also right click the opera gx shortcut on the taskbar > right click "Opera GX browser" and choose properties, it should show the target like the image below.

![image](https://github.com/YoruAlptraum/no-splash-opera-gx/assets/72313676/447b5b97-2b5b-4014-b0b7-62d8cdb15b9f)
![image](https://github.com/YoruAlptraum/no-splash-opera-gx/assets/72313676/4da1da0b-422f-4b5f-bda0-8e5e492b81a6)


 I'll be updating the setup to prompt a message to make it more intuitive.

**Comment by YoruAlptraum** [comment]
I updated the setup script to pop up a message confirming the script was executed so I'll be closing this issue, thank you for your feedback. 
If you find any other issues let me know.
